name: Auto Build & Commit dist on Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Commit dist/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if ! git diff --quiet --cached; then
            # extract tag name (for push event) or release tag (for release event)
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "🚀 Building and committing dist for $TAG_NAME"
            git commit -m "🚀 Build dist for $TAG_NAME [skip ci]"
            git push
          else
            echo "No changes in dist/, skipping commit."
          fi
