name: Build Dist and Push to Main

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install & Build
        run: |
          npm ci
          npm run build   # emits ./dist

      - name: Commit dist/ to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if git diff --cached --quiet; then
            echo "✅ No changes in dist/, skipping commit."
          else
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            git commit -m "📦 Build dist for $TAG_NAME [skip ci]"
            git push origin main
          fi
