# .github/workflows/auto-build-dist.yml
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Commit built dist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Remove any old dist and add the new one
          git rm -r --ignore-unmatch dist
          git add dist

          # Force a commit no matter what, even if nothing changed
          TAG=${{ github.ref_name }}
          git commit --allow-empty -m "📦 Publish dist for ${TAG} [skip ci]"

          # Push back to the same tag
          git push origin ${TAG}
