# .github/workflows/auto-build-dist.yml
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Commit dist and update tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Clean out old dist (if any) and stage new
          git rm -r --ignore-unmatch dist
          git add dist

          TAG=${{ github.ref_name }}

          # Always commit, even if nothing changed
          git commit --allow-empty -m "📦 Publish dist for ${TAG} [skip ci]"

          # Force-update the remote tag to point at this new commit
          git push --force origin HEAD:refs/tags/${TAG}
